import logging
from typing import Optional

import torch
from torch import nn


def count_parameters(model: nn.Module) -> int:
    """Count the number of trainable parameters in a given model.

    Args:
        model (nn.Module)
    Returns:
        n_parameters: the total count of trainable model parameters.
    """
    n_parameters = sum(p.numel() for p in model.parameters() if p.requires_grad)
    return n_parameters


def get_device(priority: Optional[str] = None) -> str:
    """Get the torch device to use for training.

    Prioritizes the selected device, if available. Otherwise, will
    follow the given ranking (highest priority to leftmost device):

    `[priority]` >> `cuda` >> `mps` >> `cpu`

    Returns:
        str: device
    """
    devices = ["cpu"]
    if torch.backends.mps.is_available():
        devices.append("mps")
    if torch.cuda.is_available():
        devices.append("cuda")

    # if user specified a device preference
    if priority:
        if priority in devices:
            selected_device = priority
        else:
            selected_device = devices[-1]
            logging.info(
                "Device '{}' not available, resorting to '{}'",
                priority,
                selected_device,
            )
        return selected_device

    # otherwise, return highest ranking available device
    return devices[-1]


def mixin_uniform(probs: torch.Tensor, split=0.01, dim=-1) -> torch.Tensor:
    """Mixes a uniform distribution with the given probabilities.

    For a probability distribution with N outcomes, the mixed distribution
    will have probabilities:

    p_i = (1 - split)*p_i + (split)*1/N

    Args:
        probs (*): the tensor of probabilities.
        split (float): percentage assigned to uniform distribution. Defaults to 0.01.
        dim (int): tensor probability dimension. Defaults to -1, i.e. last dimension.

    Returns:
        torch.Tensor: mixed probability distribution.
    """
    # create uniform distribution over specified dimension
    uniform = torch.ones_like(probs) / probs.shape[dim]
    # mix uniform with given distribution
    mixed = (1 - split) * probs + split * uniform
    return mixed


def symlog(x: torch.Tensor) -> torch.Tensor:
    """Compute symlog function.

    Eq (9) in paper.

    Args:
        x (*): input tensor.
    Returns:
        y (*): output tensor.
    """
    y = torch.sign(x) * torch.log(torch.abs(x) + 1)
    return y


def symexp(x: torch.Tensor) -> torch.Tensor:
    """Compute sympexp function.

    Eq (9) in paper.

    Args:
        x (*): input tensor.
    Returns:
        y (*): output tensor.
    """
    y = torch.sign(x) * (torch.exp(torch.abs(x)) - 1)
    return y


def calculate_lambda_returns(rewards, continues, values, gamma=0.997, lamda=0.95):
    """Calculate lambda returns for a given sequence.

    Eq (5) in paper.

    Lamda parameter controls the decay of returns across the trace (sequence returns). A value
    of 1 indicates the whole trace should contribute to the return (as in
    Monte Carlo, except in this case we still are bootstrapping). A value of 0
    indicates that we should only use the next value following a reward to
    approximate the return (like in Q-learning).

    Args:
        rewards: observed rewards in batch.
        continues: soft continue flags generated by world model in batch.
        values: generated values by critic in batch.
        gamma: reward discount parameter.
        lamda: trace decay parameter.
    Returns:
        returns: bootstrapped returns over batch.
    """
    T = values.shape[-1] - 1  # last index in sequence
    returns = torch.zeros_like(rewards)

    # the return at time T is equal to the value at time T (bootstrap value)
    returns[..., T] = values[..., T]

    for t in reversed(range(T)):
        returns[..., t] = rewards[..., t] + gamma * continues[..., t] * (
            (1 - lamda) * values[..., t] + lamda * returns[..., t + 1]
        )

    return returns
