import torch


@torch.jit.script
def calculate_lambda_returns(
    rewards: torch.Tensor,
    continues: torch.Tensor,
    values: torch.Tensor,
    discount: float = 0.997,
    trace_decay: float = 0.95,
):
    """Calculate lambda returns for a given sequence of observed rewards and critic values.

    Eq (5) in paper.

    Args:
        rewards: observed rewards in batch.
        continues: soft continue flags generated by world model in batch.
        values: generated values by critic in batch.
        discount: reward discount parameter (gamma).
        trace_decay: trace decay parameter (lambda).
    Returns:
        returns: bootstrapped returns over batch.
    """
    T = values.shape[-1] - 1  # last index in sequence
    returns = torch.zeros_like(values)

    # the return at time T is equal to the value at time T (bootstrap value)
    returns[..., T] = values[..., T]

    for t in range(T - 1, -1, -1):
        bootstrap_target = (1 - trace_decay) * values[..., t] + trace_decay * returns[..., t + 1]
        returns[..., t] = rewards[..., t] + discount * continues[..., t] * bootstrap_target

    return returns
